namespace StayGreen.Core
{
    /// <summary>Alle Texte der Anwendung: Schluessel, Deutsch, Englisch.</summary>
    static class Strings
    {
        public static readonly string[][] All =
        {
            // ---- Anwendung ----
            new[] { "app.title", "StayGreen", "StayGreen" },
            new[] { "tab.activity", "Aktivität", "Activity" },
            new[] { "tab.schedule", "Zeitplan", "Schedule" },
            new[] { "tab.system", "System", "System" },
            new[] { "btn.start", "Starten", "Start" },
            new[] { "btn.stop", "Stoppen", "Stop" },
            new[] { "footer", "StayGreen {0} · hält deinen Teams-Status grün", "StayGreen {0} · keeps your Teams status green" },
            new[] { "confirm.exit",
                "StayGreen läuft noch. Wirklich beenden?\n\nDein Status wechselt danach wieder auf „Abwesend“.",
                "StayGreen is still running. Really exit?\n\nYour status will go back to \"Away\" afterwards." },
            new[] { "balloon.tray",
                "StayGreen läuft im Infobereich weiter. Ein Klick auf das Symbol öffnet das Fenster.",
                "StayGreen keeps running in the notification area. Click the icon to open the window." },

            new[] { "cli.help",
                "StayGreen [Optionen]\r\n\r\n"
                + "  --start            Aktivhalten sofort starten\r\n"
                + "  --no-start         Aktivhalten nicht automatisch starten\r\n"
                + "  --minimized        Nur im Infobereich starten (ohne Fenster)\r\n"
                + "  --settings <Datei> Andere Einstellungsdatei verwenden\r\n"
                + "  --lang de|en       Sprache für diesen Start\r\n"
                + "  --tab <Name>       Seite öffnen: activity, schedule (mit Auto-Stopp), system\r\n"
                + "  --selftest [Datei] Selbsttest ausführen und Ergebnis speichern\r\n"
                + "  --autostart        (intern) Start durch den Windows-Autostart\r\n"
                + "  --help             Diese Hilfe\r\n",
                "StayGreen [options]\r\n\r\n"
                + "  --start            Start holding right away\r\n"
                + "  --no-start         Do not start holding automatically\r\n"
                + "  --minimized        Start in the notification area only (no window)\r\n"
                + "  --settings <file>  Use a different settings file\r\n"
                + "  --lang de|en       Language for this start\r\n"
                + "  --tab <name>       Open a page: activity, schedule (incl. auto-stop), system\r\n"
                + "  --selftest [file]  Run the self-test and save the result\r\n"
                + "  --autostart        (internal) Start by Windows autostart\r\n"
                + "  --help             This help\r\n" },

            // ---- Status ----
            new[] { "status.stopped", "Gestoppt", "Stopped" },
            new[] { "status.stopped.detail",
                "Klicke auf „Starten“, damit dein Status auf „Verfügbar“ bleibt.",
                "Click \"Start\" to keep your status on \"Available\"." },
            new[] { "status.active", "Aktiv – dein Status bleibt grün", "Active – your status stays green" },
            new[] { "status.active.detail",
                "Nächste Aktion in {0} s · {1} Aktionen · läuft seit {2}",
                "Next action in {0} s · {1} actions · running for {2}" },
            new[] { "status.standby", "Bereit – du bist gerade aktiv", "Standing by – you are active" },
            new[] { "status.standby.detail",
                "Greift ein, sobald du {0} s nichts tust (Leerlauf jetzt: {1} s)",
                "Steps in once you are idle for {0} s (idle now: {1} s)" },
            new[] { "status.waiting", "Wartet auf das Zeitfenster", "Waiting for the time window" },
            new[] { "status.waiting.detail", "Nächster Start: {0}", "Next start: {0}" },
            new[] { "status.waiting.detail.none", "Kein weiteres Zeitfenster in Sicht.", "No further time window in sight." },
            new[] { "status.blocked", "Eingaben werden abgelehnt", "Input is being rejected" },
            new[] { "status.blocked.detail",
                "Windows nimmt keine Eingaben an (gesperrte Sitzung oder blockiert). Teams kann „Abwesend“ anzeigen.",
                "Windows does not accept input (locked session or blocked). Teams may show \"Away\"." },
            new[] { "status.locked", "PC gesperrt", "PC locked" },
            new[] { "status.locked.detail",
                "Solange der PC gesperrt ist, zeigt Teams „Abwesend“. Nach dem Entsperren geht es automatisch weiter.",
                "While the PC is locked, Teams shows \"Away\". It continues automatically after unlocking." },

            // ---- Planzeile ----
            new[] { "plan.schedule.until", "Zeitplan: aktiv bis {0}", "Schedule: active until {0}" },
            new[] { "plan.schedule.from", "Zeitplan: nächster Start {0}", "Schedule: next start {0}" },
            new[] { "plan.schedule.always", "Zeitplan: dauerhaft aktiv", "Schedule: always active" },
            new[] { "plan.schedule.never", "Zeitplan: kein Start in Sicht", "Schedule: no start in sight" },
            new[] { "plan.autostop", "Auto-Stopp: {0}", "Auto-stop: {0}" },
            new[] { "plan.autostop.expired", "Auto-Stopp: Termin liegt in der Vergangenheit", "Auto-stop: the time is in the past" },
            new[] { "plan.action.teams", "Teams beenden", "close Teams" },
            new[] { "plan.action.lock", "Windows sperren", "lock Windows" },
            new[] { "plan.action.shutdown", "Herunterfahren", "shut down" },
            new[] { "plan.action.exit", "StayGreen beenden", "exit StayGreen" },
            new[] { "plan.action.none", "nur das Aktivhalten stoppen", "only stop holding" },

            // ---- Zeit und Wochentage ----
            new[] { "when.today", "heute", "today" },
            new[] { "when.tomorrow", "morgen", "tomorrow" },
            new[] { "days.daily", "täglich", "daily" },
            new[] { "days.none", "kein Tag", "no day" },
            new[] { "rule.overnight", "(bis zum Folgetag)", "(until the next day)" },
            new[] { "day.0.short", "Mo", "Mon" },
            new[] { "day.1.short", "Di", "Tue" },
            new[] { "day.2.short", "Mi", "Wed" },
            new[] { "day.3.short", "Do", "Thu" },
            new[] { "day.4.short", "Fr", "Fri" },
            new[] { "day.5.short", "Sa", "Sat" },
            new[] { "day.6.short", "So", "Sun" },
            new[] { "key.ctrl", "Strg", "Ctrl" },
            new[] { "key.alt", "Alt", "Alt" },
            new[] { "key.shift", "Umschalt", "Shift" },
            new[] { "key.win", "Win", "Win" },

            // ---- Karte "Aktivität" ----
            new[] { "act.grp.method", "So bleibst du grün", "How to stay green" },
            new[] { "act.grp.behavior", "Verhalten", "Behavior" },
            new[] { "act.mode", "Methode", "Method" },
            new[] { "act.mode.key", "Tastendruck (F15), unsichtbar", "Key press (F15), invisible" },
            new[] { "act.mode.mouse", "Mausbewegung (wenige Pixel)", "Mouse movement (a few pixels)" },
            new[] { "act.mode.both", "Taste und Maus (empfohlen)", "Key and mouse (recommended)" },
            new[] { "act.interval", "Intervall", "Interval" },
            new[] { "act.unit.sec", "Sekunden", "seconds" },
            new[] { "act.pixels", "Mausweg", "Mouse travel" },
            new[] { "act.pixels.hint",
                "So weit zuckt die Maus: wenige Pixel hin und sofort zurück.",
                "How far the mouse twitches: a few pixels there and straight back." },
            new[] { "act.unit.px", "Pixel", "pixels" },
            new[] { "act.hint",
                "Teams setzt dich nach etwa 5 Minuten ohne Eingabe auf „Abwesend“. 30 bis 60 Sekunden reichen sicher.",
                "Teams sets you to \"Away\" after about 5 minutes without input. 30 to 60 seconds is plenty." },
            new[] { "act.smart", "Nur eingreifen, wenn ich selbst nichts tue", "Only act while I am idle" },
            new[] { "act.smart.hint",
                "Solange du arbeitest, bleibt StayGreen im Hintergrund. Erst wenn du länger als das Intervall nichts tust, werden Eingaben gesendet.",
                "While you work, StayGreen stays out of the way. Input is only sent once you have been idle for longer than the interval." },
            new[] { "act.awake", "PC und Bildschirm wach halten", "Keep PC and screen awake" },
            new[] { "act.awake.hint",
                "Verhindert Standby, Bildschirmschoner und das automatische Sperren bei Inaktivität. Sperrst du den PC selbst (Win+L), zeigt Teams trotzdem „Abwesend“.",
                "Prevents standby, screen saver and automatic locking due to inactivity. If you lock the PC yourself (Win+L), Teams still shows \"Away\"." },
            new[] { "act.test", "Jetzt testen", "Test now" },
            new[] { "act.test.title", "Eingabe testen", "Test input" },
            new[] { "act.test.hint",
                "Sendet jetzt eine Eingabe und zeigt, ob Windows sie annimmt.",
                "Sends an input now and shows whether Windows accepts it." },
            new[] { "act.test.ok", "Eingabe gesendet.", "Input sent." },
            new[] { "act.test.fail",
                "Windows hat die Eingabe abgelehnt (PC gesperrt oder Zugriff blockiert).",
                "Windows rejected the input (PC locked or access blocked)." },

            // ---- Karte "Zeitplan" ----
            new[] { "sch.grp.title", "Aktive Zeiten", "Active hours" },
            new[] { "sch.enable", "Nur in diesen Zeitfenstern aktiv halten", "Only keep active during these time windows" },
            new[] { "sch.hint",
                "Außerhalb der Fenster pausiert StayGreen: Teams zeigt dann wie gewohnt „Abwesend“ und der PC darf in den Standby.",
                "Outside the windows StayGreen pauses: Teams then shows \"Away\" as usual and the PC may go to standby." },
            new[] { "sch.grp.edit", "Zeitfenster bearbeiten", "Edit time window" },
            new[] { "sch.days", "Wochentage", "Weekdays" },
            new[] { "sch.from", "von", "from" },
            new[] { "sch.to", "bis", "to" },
            new[] { "sch.add", "Hinzufügen", "Add" },
            new[] { "sch.update", "Ändern", "Change" },
            new[] { "sch.remove", "Entfernen", "Remove" },
            new[] { "sch.preset", "Büro: Mo–Fr 08–17 Uhr", "Office: Mon–Fri 08–17" },
            new[] { "sch.hint.midnight",
                "Liegt das Ende vor dem Start, geht das Fenster über Mitternacht (z. B. 22:00 bis 06:00).",
                "If the end is before the start, the window spans midnight (e.g. 22:00 to 06:00)." },
            new[] { "sch.err.nodays", "Bitte mindestens einen Wochentag auswählen.", "Please select at least one weekday." },
            new[] { "sch.err.sametime", "Start und Ende dürfen nicht gleich sein.", "Start and end must not be the same." },
            new[] { "sch.none",
                "Noch kein Zeitfenster angelegt. Der Zeitplan wirkt erst, wenn es mindestens eins gibt.",
                "No time window yet. The schedule only takes effect once there is at least one." },

            // ---- Karte "Auto-Stopp" ----
            new[] { "stop.grp.title", "Feierabend: Auto-Stopp", "End of day: auto-stop" },
            new[] { "stop.enable", "StayGreen automatisch beenden", "Stop StayGreen automatically" },
            new[] { "stop.intro",
                "Beendet das Aktivhalten zur gewünschten Zeit, zum Beispiel zum Feierabend.",
                "Stops holding at the chosen time, for example at the end of the workday." },
            new[] { "stop.when", "Wann", "When" },
            new[] { "stop.mode.daily", "Täglich", "Daily" },
            new[] { "stop.mode.once", "Einmalig", "Once" },
            new[] { "stop.time", "Uhrzeit", "Time" },
            new[] { "stop.datetime", "Datum und Uhrzeit", "Date and time" },
            new[] { "stop.grp.actions", "Dabei zusätzlich", "Additionally" },
            new[] { "stop.teams", "Teams beenden", "Close Teams" },
            new[] { "stop.teams.hint",
                "Dein Status wechselt dann auf „Offline“.",
                "Your status then changes to \"Offline\"." },
            new[] { "stop.lock", "Windows sperren", "Lock Windows" },
            new[] { "stop.shutdown", "Computer herunterfahren", "Shut down the computer" },
            new[] { "stop.shutdown.hint",
                "Vorher läuft ein Countdown von 60 Sekunden, den du abbrechen kannst. Programme mit ungespeicherten Daten werden nicht zwangsweise geschlossen.",
                "A 60-second countdown runs first, which you can cancel. Programs with unsaved data are not closed by force." },
            new[] { "stop.exit", "StayGreen beenden", "Exit StayGreen" },
            new[] { "stop.exit.hint",
                "Das Programm schließt sich ganz. Am nächsten Tag läuft es nur, wenn du es startest oder der Autostart an ist.",
                "The program closes completely. Tomorrow it only runs if you start it or autostart is on." },

            // ---- Karte "System" ----
            new[] { "sys.grp.start", "Start", "Startup" },
            new[] { "sys.startonlaunch", "Beim Öffnen automatisch starten", "Start automatically when opened" },
            new[] { "sys.autostart", "Mit Windows starten (Autostart)", "Start with Windows (autostart)" },
            new[] { "sys.autostart.hint",
                "Ohne Administratorrechte, nur für dein Benutzerkonto.",
                "No administrator rights needed, only for your user account." },
            new[] { "sys.autostart.fail",
                "Der Autostart konnte nicht eingerichtet werden (möglicherweise durch eine Richtlinie blockiert).",
                "Autostart could not be set up (possibly blocked by a policy)." },
            new[] { "sys.startmin", "Minimiert starten (nur Infobereich)", "Start minimized (notification area only)" },
            new[] { "sys.tray", "In den Infobereich minimieren", "Minimize to the notification area" },
            new[] { "sys.grp.log", "Protokoll", "Log" },
            new[] { "sys.log", "Start und Stopp in eine Textdatei schreiben", "Write start and stop to a text file" },
            new[] { "sys.log.open", "Öffnen", "Open" },
            new[] { "sys.log.change", "Ändern …", "Change …" },
            new[] { "sys.log.nofile", "Die Protokolldatei existiert noch nicht:\n{0}", "The log file does not exist yet:\n{0}" },
            new[] { "sys.log.browse.title", "Protokolldatei wählen", "Choose log file" },
            new[] { "sys.log.browse.filter",
                "Textdateien (*.txt)|*.txt|Alle Dateien (*.*)|*.*",
                "Text files (*.txt)|*.txt|All files (*.*)|*.*" },
            new[] { "sys.grp.hotkey", "Tastenkombination", "Hotkey" },
            new[] { "sys.hotkey", "Globale Tastenkombination zum Starten/Stoppen", "Global hotkey to start/stop" },
            new[] { "sys.hotkey.ok", "Aktiv: {0}", "Active: {0}" },
            new[] { "sys.hotkey.fail",
                "{0} konnte nicht angemeldet werden (schon von einem anderen Programm belegt?).",
                "{0} could not be registered (already used by another program?)." },
            new[] { "sys.grp.general", "Sprache und Daten", "Language and data" },
            new[] { "sys.language", "Sprache", "Language" },
            new[] { "sys.lang.auto", "Automatisch (Windows)", "Automatic (Windows)" },
            new[] { "sys.folder", "Einstellungsordner", "Settings folder" },
            new[] { "sys.portable",
                "Portabler Modus: Die Einstellungen liegen neben der EXE.",
                "Portable mode: settings are stored next to the EXE." },

            // ---- Tray ----
            new[] { "tray.show", "Fenster anzeigen", "Show window" },
            new[] { "tray.autostart", "Mit Windows starten", "Start with Windows" },
            new[] { "tray.exit", "Beenden", "Exit" },

            // ---- Countdown vor dem Herunterfahren ----
            new[] { "cd.title", "Computer wird heruntergefahren", "Computer is shutting down" },
            new[] { "cd.text",
                "StayGreen hat den Auto-Stopp erreicht. Der Computer wird in {0} Sekunden heruntergefahren.",
                "StayGreen reached the auto-stop. The computer will shut down in {0} seconds." },
            new[] { "cd.now", "Jetzt herunterfahren", "Shut down now" },
            new[] { "cd.cancel", "Abbrechen", "Cancel" },

            // ---- Protokoll ----
            new[] { "reason.manual", "Manuell", "Manual" },
            new[] { "reason.hotkey", "Hotkey", "Hotkey" },
            new[] { "reason.tray", "Tray-Menü", "Tray menu" },
            new[] { "reason.launch", "Programmstart", "Program start" },
            new[] { "reason.autostart", "Windows-Autostart", "Windows autostart" },
            new[] { "reason.autostop", "Auto-Stopp", "Auto-stop" },
            new[] { "reason.exit", "Programm beendet", "Program exited" },
            new[] { "log.runtime", "Laufzeit {0}", "Runtime {0}" },
            new[] { "log.pause_schedule", "Außerhalb des Zeitfensters, pausiert", "Outside the time window, paused" },
            new[] { "log.resume_schedule", "Zeitfenster beginnt, aktiv", "Time window started, active" },
            new[] { "log.autostop", "Auto-Stopp erreicht: {0}", "Auto-stop reached: {0}" },
            new[] { "log.autostop.missed",
                "Auto-Stopp verpasst (Rechner war nicht aktiv), übersprungen",
                "Auto-stop missed (computer was not active), skipped" },
            new[] { "log.teams.closed", "Teams beendet", "Teams closed" },
            new[] { "log.shutdown.cancelled", "Herunterfahren abgebrochen", "Shutdown cancelled" },
            new[] { "log.shutdown", "Computer wird heruntergefahren", "Computer is shutting down" },
            new[] { "log.locked", "Windows gesperrt", "Windows locked" },
            new[] { "log.exit", "StayGreen beendet", "StayGreen exited" },
        };
    }
}
