namespace StayGreen.Core
{
    /// <summary>Alle Texte der Anwendung: Schluessel, Deutsch, Englisch.</summary>
    static class Strings
    {
        public static readonly string[][] All =
        {
            // ---- Anwendung ----
            new[] { "app.title", "StayGreen", "StayGreen" },
            new[] { "tab.activity", "Aktivität", "Activity" },
            new[] { "tab.schedule", "Zeitplan", "Schedule" },
            new[] { "tab.system", "System", "System" },
            new[] { "btn.start", "Starten", "Start" },
            new[] { "btn.stop", "Stoppen", "Stop" },
            new[] { "btn.resume", "Fortsetzen", "Resume" },
            new[] { "footer", "StayGreen {0} · hält deinen Teams-Status grün", "StayGreen {0} · keeps your Teams status green" },
            new[] { "confirm.exit",
                "StayGreen läuft noch. Wirklich beenden?\n\nDein Status wechselt danach wieder auf „Abwesend“.",
                "StayGreen is still running. Really exit?\n\nYour status will go back to \"Away\" afterwards." },
            new[] { "balloon.tray",
                "StayGreen läuft im Infobereich weiter. Ein Klick auf das Symbol öffnet das Fenster.",
                "StayGreen keeps running in the notification area. Click the icon to open the window." },
            new[] { "balloon.maxruntime",
                "StayGreen wurde nach {0} automatisch gestoppt (Sicherheitsnetz).",
                "StayGreen stopped automatically after {0} (safety net)." },
            new[] { "balloon.storage",
                "Die Einstellungen konnten nicht gespeichert werden: {0}",
                "Settings could not be saved: {0}" },
            new[] { "balloon.log",
                "Das Protokoll konnte nicht geschrieben werden: {0}",
                "The log could not be written: {0}" },

            new[] { "notice.title", "Hinweis zur Nutzung", "Notice" },
            new[] { "notice.text",
                "StayGreen simuliert Eingaben und verhindert Standby sowie die automatische Sperre. Dein PC bleibt dadurch entsperrt, wenn du weggehst.\n\n"
                + "Nutze StayGreen nur, wo die Regeln deines Arbeitgebers das erlauben, und sperre den PC (Win+L), wenn du länger weg bist.",
                "StayGreen simulates input and prevents standby and the automatic lock. Your PC therefore stays unlocked when you walk away.\n\n"
                + "Only use StayGreen where your employer's rules allow it, and lock your PC (Win+L) when you are away for longer." },

            new[] { "cli.help",
                "StayGreen [Optionen]\r\n\r\n"
                + "  --start            Aktivhalten starten (auch in einer laufenden Instanz)\r\n"
                + "  --stop             Aktivhalten stoppen (auch in einer laufenden Instanz)\r\n"
                + "  --toggle           Zwischen Start und Stopp umschalten\r\n"
                + "  --pause [Minuten]  Für eine Weile pausieren (Standard 30)\r\n"
                + "  --resume           Eine Pause beenden\r\n"
                + "  --no-start         Aktivhalten nicht automatisch starten\r\n"
                + "  --minimized        Nur im Infobereich starten (ohne Fenster)\r\n"
                + "  --settings <Datei> Andere Einstellungsdatei verwenden\r\n"
                + "  --lang de|en       Sprache für diesen Start\r\n"
                + "  --theme light|dark|auto  Darstellung für diesen Start\r\n"
                + "  --tab <Name>       Seite öffnen: activity, schedule (mit Auto-Stopp), system\r\n"
                + "  --selftest [Datei] Selbsttest ausführen und Ergebnis speichern\r\n"
                + "  --autostart        (intern) Start durch den Windows-Autostart\r\n"
                + "  --help             Diese Hilfe\r\n",
                "StayGreen [options]\r\n\r\n"
                + "  --start            Start holding (also in a running instance)\r\n"
                + "  --stop             Stop holding (also in a running instance)\r\n"
                + "  --toggle           Switch between start and stop\r\n"
                + "  --pause [minutes]  Pause for a while (default 30)\r\n"
                + "  --resume           End a pause\r\n"
                + "  --no-start         Do not start holding automatically\r\n"
                + "  --minimized        Start in the notification area only (no window)\r\n"
                + "  --settings <file>  Use a different settings file\r\n"
                + "  --lang de|en       Language for this start\r\n"
                + "  --theme light|dark|auto  Appearance for this start\r\n"
                + "  --tab <name>       Open a page: activity, schedule (incl. auto-stop), system\r\n"
                + "  --selftest [file]  Run the self-test and save the result\r\n"
                + "  --autostart        (internal) Start by Windows autostart\r\n"
                + "  --help             This help\r\n" },

            // ---- Status ----
            new[] { "status.stopped", "Gestoppt", "Stopped" },
            new[] { "status.stopped.detail",
                "Klicke auf „Starten“, damit dein Status auf „Verfügbar“ bleibt.",
                "Click \"Start\" to keep your status on \"Available\"." },
            new[] { "status.active", "Aktiv – dein Status bleibt grün", "Active – your status stays green" },
            new[] { "status.active.detail",
                "Nächste Aktion in {0} s · {1} Aktionen · läuft seit {2}",
                "Next action in {0} s · {1} actions · running for {2}" },
            new[] { "status.standby", "Bereit – du bist gerade aktiv", "Standing by – you are active" },
            new[] { "status.standby.detail",
                "Greift ein, sobald du {0} s nichts tust (Leerlauf jetzt: {1} s)",
                "Steps in once you are idle for {0} s (idle now: {1} s)" },
            new[] { "status.paused", "Pausiert", "Paused" },
            new[] { "status.paused.detail",
                "Läuft automatisch weiter: {0}",
                "Resumes automatically: {0}" },
            new[] { "status.paused.detail.open",
                "Läuft weiter, sobald du die Pause beendest.",
                "Continues as soon as you end the pause." },
            new[] { "status.waiting", "Wartet auf das Zeitfenster", "Waiting for the time window" },
            new[] { "status.waiting.detail", "Nächster Start: {0}", "Next start: {0}" },
            new[] { "status.waiting.detail.none", "Kein weiteres Zeitfenster in Sicht.", "No further time window in sight." },
            new[] { "status.teams", "Wartet auf Teams", "Waiting for Teams" },
            new[] { "status.teams.detail",
                "StayGreen greift ein, sobald Teams läuft.",
                "StayGreen steps in as soon as Teams is running." },
            new[] { "status.blocked", "Eingaben werden abgelehnt", "Input is being rejected" },
            new[] { "status.blocked.detail",
                "Windows nimmt keine Eingaben an (gesperrte Sitzung oder blockiert). Teams kann „Abwesend“ anzeigen.",
                "Windows does not accept input (locked session or blocked). Teams may show \"Away\"." },
            new[] { "status.locked", "PC gesperrt", "PC locked" },
            new[] { "status.locked.detail",
                "Solange der PC gesperrt ist, zeigt Teams „Abwesend“. Nach dem Entsperren geht es automatisch weiter.",
                "While the PC is locked, Teams shows \"Away\". It continues automatically after unlocking." },

            // ---- Planzeile ----
            new[] { "plan.schedule.until", "Zeitplan: aktiv bis {0}", "Schedule: active until {0}" },
            new[] { "plan.schedule.from", "Zeitplan: nächster Start {0}", "Schedule: next start {0}" },
            new[] { "plan.schedule.always", "Zeitplan: dauerhaft aktiv", "Schedule: always active" },
            new[] { "plan.schedule.never", "Zeitplan: kein Start in Sicht", "Schedule: no start in sight" },
            new[] { "plan.autostop", "Auto-Stopp: {0}", "Auto-stop: {0}" },
            new[] { "plan.autostop.expired", "Auto-Stopp: Termin liegt in der Vergangenheit", "Auto-stop: the time is in the past" },
            new[] { "plan.autostop.noschedule", "Auto-Stopp: Zeitplan fehlt", "Auto-stop: needs a schedule" },
            new[] { "plan.autostop.noend", "Auto-Stopp: kein Zeitplan-Ende in Sicht", "Auto-stop: no schedule end in sight" },
            new[] { "plan.action.teams", "Teams beenden", "close Teams" },
            new[] { "plan.action.lock", "Windows sperren", "lock Windows" },
            new[] { "plan.action.shutdown", "Herunterfahren", "shut down" },
            new[] { "plan.action.exit", "StayGreen beenden", "exit StayGreen" },
            new[] { "plan.action.none", "nur das Aktivhalten stoppen", "only stop holding" },

            // ---- Zeit und Wochentage ----
            new[] { "when.today", "heute", "today" },
            new[] { "when.tomorrow", "morgen", "tomorrow" },
            new[] { "days.daily", "täglich", "daily" },
            new[] { "days.none", "kein Tag", "no day" },
            new[] { "rule.overnight", "(bis zum Folgetag)", "(until the next day)" },
            new[] { "day.0.short", "Mo", "Mon" },
            new[] { "day.1.short", "Di", "Tue" },
            new[] { "day.2.short", "Mi", "Wed" },
            new[] { "day.3.short", "Do", "Thu" },
            new[] { "day.4.short", "Fr", "Fri" },
            new[] { "day.5.short", "Sa", "Sat" },
            new[] { "day.6.short", "So", "Sun" },
            new[] { "key.ctrl", "Strg", "Ctrl" },
            new[] { "key.alt", "Alt", "Alt" },
            new[] { "key.shift", "Umschalt", "Shift" },
            new[] { "key.win", "Win", "Win" },

            // ---- Karte "Aktivität" ----
            new[] { "act.grp.method", "So bleibst du grün", "How to stay green" },
            new[] { "act.grp.behavior", "Verhalten", "Behavior" },
            new[] { "act.grp.pause", "Pause", "Pause" },
            new[] { "act.mode", "Methode", "Method" },
            new[] { "act.mode.key", "Tastendruck, unauffällig", "Key press, unobtrusive" },
            new[] { "act.mode.mouse", "Mausbewegung (wenige Pixel)", "Mouse movement (a few pixels)" },
            new[] { "act.mode.both", "Taste und Maus (empfohlen)", "Key and mouse (recommended)" },
            new[] { "act.key", "Taste", "Key" },
            new[] { "act.key.hint",
                "F13 bis F24 gibt es auf kaum einer Tastatur. Die Umschalttaste stört auch in Terminals und Remote-Sitzungen nicht.",
                "F13 to F24 hardly exist on any keyboard. The Shift key is harmless even in terminals and remote sessions." },
            new[] { "act.key.shift", "Umschalttaste (Shift)", "Shift key" },
            new[] { "act.interval", "Intervall", "Interval" },
            new[] { "act.unit.sec", "Sekunden", "seconds" },
            new[] { "act.pixels", "Mausweg", "Mouse travel" },
            new[] { "act.pixels.hint",
                "So weit zuckt die Maus: wenige Pixel hin und sofort zurück.",
                "How far the mouse twitches: a few pixels there and straight back." },
            new[] { "act.unit.px", "Pixel", "pixels" },
            new[] { "act.hint",
                "Teams setzt dich nach etwa 5 Minuten ohne Eingabe auf „Abwesend“. 30 bis 60 Sekunden reichen sicher.",
                "Teams sets you to \"Away\" after about 5 minutes without input. 30 to 60 seconds is plenty." },
            new[] { "act.interval.warn",
                "Achtung: Teams setzt dich nach etwa 5 Minuten auf „Abwesend“. Bei {0} Sekunden Abstand klappt das nicht zuverlässig.",
                "Warning: Teams sets you to \"Away\" after about 5 minutes. With {0} seconds between inputs this is not reliable." },
            new[] { "act.smart", "Nur eingreifen, wenn ich selbst nichts tue", "Only act while I am idle" },
            new[] { "act.smart.hint",
                "Solange du arbeitest, bleibt StayGreen im Hintergrund. Erst wenn du länger als das Intervall nichts tust, werden Eingaben gesendet.",
                "While you work, StayGreen stays out of the way. Input is only sent once you have been idle for longer than the interval." },
            new[] { "act.awake", "PC und Bildschirm wach halten", "Keep PC and screen awake" },
            new[] { "act.awake.hint",
                "Verhindert Standby, Bildschirmschoner und das automatische Sperren bei Inaktivität. Dein PC bleibt dann entsperrt, wenn du weggehst. Sperrst du ihn selbst (Win+L), zeigt Teams trotzdem „Abwesend“.",
                "Prevents standby, screen saver and automatic locking due to inactivity. Your PC then stays unlocked when you walk away. If you lock it yourself (Win+L), Teams still shows \"Away\"." },
            new[] { "act.teamsonly", "Nur aktiv halten, solange Teams läuft", "Only hold while Teams is running" },
            new[] { "act.teamsonly.hint",
                "Ist Teams beendet, bleibt StayGreen im Wartezustand und der PC darf in den Standby.",
                "While Teams is closed, StayGreen waits and the PC may go to standby." },
            new[] { "act.maxrun", "Sicherheitsnetz: automatisch stoppen nach", "Safety net: stop automatically after" },
            new[] { "act.maxrun.hint",
                "Stoppt das Aktivhalten, wenn es so lange am Stück gelaufen ist (falls du vergisst, es auszuschalten). 0 = aus.",
                "Stops holding once it has been running for this long in a row (in case you forget to switch it off). 0 = off." },
            new[] { "act.maxrun.unit", "Stunden", "hours" },
            new[] { "act.pause", "Kurz pausieren", "Pause for a while" },
            new[] { "act.pause.hint",
                "Hält StayGreen an und macht danach von selbst weiter. Das geht auch über das Symbol im Infobereich.",
                "Pauses StayGreen and carries on by itself afterwards. Also available from the notification-area icon." },
            new[] { "act.test", "Jetzt testen", "Test now" },
            new[] { "act.test.title", "Eingabe testen", "Test input" },
            new[] { "act.test.hint",
                "Sendet jetzt eine Eingabe und zeigt, ob Windows sie annimmt.",
                "Sends an input now and shows whether Windows accepts it." },
            new[] { "act.test.ok", "Eingabe gesendet.", "Input sent." },
            new[] { "act.test.fail",
                "Windows hat die Eingabe abgelehnt (PC gesperrt oder Zugriff blockiert).",
                "Windows rejected the input (PC locked or access blocked)." },

            // ---- Karte "Zeitplan" ----
            new[] { "sch.grp.title", "Aktive Zeiten", "Active hours" },
            new[] { "sch.enable", "Nur in diesen Zeitfenstern aktiv halten", "Only keep active during these time windows" },
            new[] { "sch.hint",
                "Außerhalb der Fenster pausiert StayGreen: Teams zeigt dann wie gewohnt „Abwesend“ und der PC darf in den Standby.",
                "Outside the windows StayGreen pauses: Teams then shows \"Away\" as usual and the PC may go to standby." },
            new[] { "sch.grp.edit", "Zeitfenster bearbeiten", "Edit time window" },
            new[] { "sch.days", "Wochentage", "Weekdays" },
            new[] { "sch.from", "von", "from" },
            new[] { "sch.to", "bis", "to" },
            new[] { "sch.add", "Hinzufügen", "Add" },
            new[] { "sch.update", "Ändern", "Change" },
            new[] { "sch.remove", "Entfernen", "Remove" },
            new[] { "sch.preset", "Büro: Mo–Fr 08–17 Uhr", "Office: Mon–Fri 08–17" },
            new[] { "sch.hint.midnight",
                "Liegt das Ende vor dem Start, geht das Fenster über Mitternacht (z. B. 22:00 bis 06:00).",
                "If the end is before the start, the window spans midnight (e.g. 22:00 to 06:00)." },
            new[] { "sch.err.nodays", "Bitte mindestens einen Wochentag auswählen.", "Please select at least one weekday." },
            new[] { "sch.err.sametime", "Start und Ende dürfen nicht gleich sein.", "Start and end must not be the same." },
            new[] { "sch.none",
                "Noch kein Zeitfenster angelegt. Der Zeitplan wirkt erst, wenn es mindestens eins gibt.",
                "No time window yet. The schedule only takes effect once there is at least one." },

            // ---- Karte "Ausnahmen" ----
            new[] { "exc.grp", "Urlaub und Feiertage", "Vacation and holidays" },
            new[] { "exc.hint",
                "An diesen Tagen pausiert StayGreen, auch wenn der Zeitplan sonst aktiv wäre.",
                "StayGreen pauses on these days even if the schedule would otherwise be active." },
            new[] { "exc.none", "Keine Ausnahmen eingetragen.", "No exceptions yet." },
            new[] { "exc.days.one", "1 Tag", "1 day" },
            new[] { "exc.days.many", "{0} Tage", "{0} days" },
            new[] { "exc.err.order", "Das Ende darf nicht vor dem Anfang liegen.", "The end must not be before the start." },

            // ---- Karte "Auto-Stopp" ----
            new[] { "stop.grp.title", "Feierabend: Auto-Stopp", "End of day: auto-stop" },
            new[] { "stop.enable", "StayGreen automatisch beenden", "Stop StayGreen automatically" },
            new[] { "stop.intro",
                "Beendet das Aktivhalten zur gewünschten Zeit, zum Beispiel zum Feierabend.",
                "Stops holding at the chosen time, for example at the end of the workday." },
            new[] { "stop.when", "Wann", "When" },
            new[] { "stop.mode.daily", "Täglich", "Daily" },
            new[] { "stop.mode.once", "Einmalig", "Once" },
            new[] { "stop.mode.schedule", "Am Zeitplanende", "At schedule end" },
            new[] { "stop.schedule.hint",
                "Löst am Ende des letzten Zeitfensters eines Tages aus. Pausen unter 3 Stunden (z. B. Mittag) zählen nicht.",
                "Fires at the end of the last time window of a day. Breaks shorter than 3 hours (e.g. lunch) do not count." },
            new[] { "stop.time", "Uhrzeit", "Time" },
            new[] { "stop.datetime", "Datum und Uhrzeit", "Date and time" },
            new[] { "stop.grp.actions", "Dabei zusätzlich", "Additionally" },
            new[] { "stop.teams", "Teams beenden", "Close Teams" },
            new[] { "stop.teams.hint",
                "Dein Status wechselt dann auf „Offline“. Ein laufender Anruf wird dabei beendet.",
                "Your status then changes to \"Offline\". A running call is ended." },
            new[] { "stop.lock", "Windows sperren", "Lock Windows" },
            new[] { "stop.shutdown", "Computer herunterfahren", "Shut down the computer" },
            new[] { "stop.shutdown.hint",
                "Programme mit ungespeicherten Daten werden nicht zwangsweise geschlossen.",
                "Programs with unsaved data are not closed by force." },
            new[] { "stop.exit", "StayGreen beenden", "Exit StayGreen" },
            new[] { "stop.exit.hint",
                "Das Programm schließt sich ganz. Am nächsten Tag läuft es nur, wenn du es startest oder der Autostart an ist.",
                "The program closes completely. Tomorrow it only runs if you start it or autostart is on." },
            new[] { "stop.warn", "Vorwarnung", "Warning" },
            new[] { "stop.warn.unit", "Sekunden vorher", "seconds before" },
            new[] { "stop.warn.hint",
                "Vor „Teams beenden“, „Windows sperren“ und „Herunterfahren“ erscheint ein Countdown, den du abbrechen oder verschieben kannst.",
                "Before \"Close Teams\", \"Lock Windows\" and \"Shut down\" a countdown appears that you can cancel or postpone." },
            new[] { "stop.snooze", "Verschieben um", "Postpone by" },
            new[] { "stop.snooze.unit", "Minuten", "minutes" },

            // ---- Karte "System" ----
            new[] { "sys.grp.start", "Start", "Startup" },
            new[] { "sys.startonlaunch", "Beim Öffnen automatisch starten", "Start automatically when opened" },
            new[] { "sys.autostart", "Mit Windows starten (Autostart)", "Start with Windows (autostart)" },
            new[] { "sys.autostart.hint",
                "Ohne Administratorrechte, nur für dein Benutzerkonto.",
                "No administrator rights needed, only for your user account." },
            new[] { "sys.autostart.fail",
                "Der Autostart konnte nicht eingerichtet werden (möglicherweise durch eine Richtlinie blockiert).",
                "Autostart could not be set up (possibly blocked by a policy)." },
            new[] { "sys.startmin", "Minimiert starten (nur Infobereich)", "Start minimized (notification area only)" },
            new[] { "sys.tray", "In den Infobereich minimieren", "Minimize to the notification area" },
            new[] { "sys.grp.log", "Protokoll", "Log" },
            new[] { "sys.log", "Start und Stopp in eine Textdatei schreiben", "Write start and stop to a text file" },
            new[] { "sys.log.hint",
                "Standard: im Einstellungsordner. Der Ordner „Dokumente“ wird auf vielen PCs in die Cloud synchronisiert.",
                "Default: in the settings folder. The \"Documents\" folder is synced to the cloud on many PCs." },
            new[] { "sys.log.open", "Öffnen", "Open" },
            new[] { "sys.log.change", "Ändern …", "Change …" },
            new[] { "sys.log.nofile", "Die Protokolldatei existiert noch nicht:\n{0}", "The log file does not exist yet:\n{0}" },
            new[] { "sys.log.browse.title", "Protokolldatei wählen", "Choose log file" },
            new[] { "sys.log.browse.filter",
                "Textdateien (*.txt)|*.txt|Alle Dateien (*.*)|*.*",
                "Text files (*.txt)|*.txt|All files (*.*)|*.*" },
            new[] { "sys.log.fail", "Protokoll nicht beschreibbar: {0}", "Log not writable: {0}" },
            new[] { "sys.grp.hotkey", "Tastenkombination", "Hotkey" },
            new[] { "sys.hotkey", "Globale Tastenkombination zum Starten/Stoppen", "Global hotkey to start/stop" },
            new[] { "sys.hotkey.ok", "Aktiv: {0}", "Active: {0}" },
            new[] { "sys.hotkey.fail",
                "{0} konnte nicht angemeldet werden (schon von einem anderen Programm belegt?).",
                "{0} could not be registered (already used by another program?)." },
            new[] { "sys.hotkey.conflict",
                "{0} würde auf deiner Tastatur das Zeichen „{1}“ tippen (AltGr). Wähle eine andere Taste oder nimm Umschalt dazu.",
                "{0} would type the character \"{1}\" on your keyboard (AltGr). Pick a different key or add Shift." },
            new[] { "sys.grp.general", "Sprache und Daten", "Language and data" },
            new[] { "sys.language", "Sprache", "Language" },
            new[] { "sys.lang.auto", "Automatisch (Windows)", "Automatic (Windows)" },
            new[] { "sys.theme", "Darstellung", "Appearance" },
            new[] { "sys.theme.auto", "Automatisch (Windows)", "Automatic (Windows)" },
            new[] { "sys.theme.light", "Hell", "Light" },
            new[] { "sys.theme.dark", "Dunkel", "Dark" },
            new[] { "sys.folder", "Einstellungsordner", "Settings folder" },
            new[] { "sys.portable",
                "Portabler Modus: Die Einstellungen liegen neben der EXE.",
                "Portable mode: settings are stored next to the EXE." },
            new[] { "sys.storage.fail",
                "Einstellungen konnten nicht gespeichert werden: {0}",
                "Settings could not be saved: {0}" },
            new[] { "sys.update", "Neue Version", "New version" },
            new[] { "sys.update.hint",
                "Öffnet die Release-Seite im Browser. StayGreen selbst baut nie eine Verbindung auf.",
                "Opens the release page in your browser. StayGreen itself never connects to the internet." },
            new[] { "sys.update.open", "Suchen", "Check" },

            // ---- Tray ----
            new[] { "tray.show", "Fenster anzeigen", "Show window" },
            new[] { "tray.autostart", "Mit Windows starten", "Start with Windows" },
            new[] { "tray.exit", "Beenden", "Exit" },
            new[] { "tray.pause", "Pausieren", "Pause" },
            new[] { "tray.pause.minutes", "{0} Minuten", "{0} minutes" },
            new[] { "tray.pause.hour", "1 Stunde", "1 hour" },
            new[] { "tray.pause.hours", "{0} Stunden", "{0} hours" },
            new[] { "tray.resume", "Fortsetzen", "Resume" },
            new[] { "tray.skiptoday", "Heute aussetzen", "Skip today" },
            new[] { "tray.unskiptoday", "Heute wieder aktivieren", "Re-enable today" },

            // ---- Vorwarnung vor dem Auto-Stopp ----
            new[] { "cd.title", "Auto-Stopp in Kürze", "Auto-stop coming up" },
            new[] { "cd.text",
                "StayGreen führt in {0} Sekunden den Auto-Stopp aus: {1}.",
                "StayGreen runs the auto-stop in {0} seconds: {1}." },
            new[] { "cd.now", "Jetzt ausführen", "Run now" },
            new[] { "cd.snooze", "{0} Min. verschieben", "Postpone {0} min" },
            new[] { "cd.cancel", "Abbrechen", "Cancel" },

            // ---- Protokoll ----
            new[] { "reason.manual", "Manuell", "Manual" },
            new[] { "reason.hotkey", "Hotkey", "Hotkey" },
            new[] { "reason.tray", "Tray-Menü", "Tray menu" },
            new[] { "reason.command", "Befehlszeile", "Command line" },
            new[] { "reason.launch", "Programmstart", "Program start" },
            new[] { "reason.autostart", "Windows-Autostart", "Windows autostart" },
            new[] { "reason.autostop", "Auto-Stopp", "Auto-stop" },
            new[] { "reason.exit", "Programm beendet", "Program exited" },
            new[] { "reason.maxruntime", "Maximale Laufzeit erreicht ({0})", "Maximum runtime reached ({0})" },
            new[] { "log.runtime", "Laufzeit {0}", "Runtime {0}" },
            new[] { "log.pause_schedule", "Außerhalb des Zeitfensters, pausiert", "Outside the time window, paused" },
            new[] { "log.pause_manual", "Pausiert bis {0} ({1})", "Paused until {0} ({1})" },
            new[] { "log.pause_teams", "Teams läuft nicht, pausiert", "Teams is not running, paused" },
            new[] { "log.resume_schedule", "Zeitfenster beginnt, aktiv", "Time window started, active" },
            new[] { "log.resume_pause", "Pause beendet, aktiv", "Pause over, active" },
            new[] { "log.resume_teams", "Teams läuft, aktiv", "Teams is running, active" },
            new[] { "log.blocked",
                "Windows lehnt Eingaben ab (gesperrte Sitzung oder blockiert)",
                "Windows rejects input (locked session or blocked)" },
            new[] { "log.unblocked", "Eingaben werden wieder angenommen", "Input is accepted again" },
            new[] { "log.session.lock", "Sitzung gesperrt oder getrennt", "Session locked or disconnected" },
            new[] { "log.session.unlock", "Sitzung entsperrt oder verbunden", "Session unlocked or connected" },
            new[] { "log.sleep", "Rechner geht in den Standby", "Computer is going to sleep" },
            new[] { "log.wake", "Rechner ist aufgewacht", "Computer woke up" },
            new[] { "log.autostop", "Auto-Stopp erreicht: {0}", "Auto-stop reached: {0}" },
            new[] { "log.autostop.missed",
                "Auto-Stopp verpasst (Rechner war nicht aktiv), übersprungen",
                "Auto-stop missed (computer was not active), skipped" },
            new[] { "log.autostop.cancelled", "Auto-Stopp abgebrochen", "Auto-stop cancelled" },
            new[] { "log.autostop.snoozed",
                "Auto-Stopp um {0} Minuten auf {1} verschoben",
                "Auto-stop postponed by {0} minutes to {1}" },
            new[] { "log.teams.closed", "Teams beendet", "Teams closed" },
            new[] { "log.shutdown", "Computer wird heruntergefahren", "Computer is shutting down" },
            new[] { "log.locked", "Windows gesperrt", "Windows locked" },
            new[] { "log.exit", "StayGreen beendet", "StayGreen exited" },
        };
    }
}
